### ISSUE TITLE
Add ktest

### ISSUE THREAD

**Issue by i582** [quasilyte/awesome-kphp#1]
One great guy and programmer wrote a amazingly awesome testing and benchmarking [tool](https://github.com/quasilyte/ktest) for KPHP, if he doesn't mind, you can add his tool here 😄

**Comment by quasilyte** [comment]
Oh. I just noticed this issue.
ktest is already in the list. :+1: 
I think we need to add `nocolor` by some other great guy and programmer. :)

**Comment by i582** [comment]
> Oh. I just noticed this issue.
> ktest is already in the list. 👍
> I think we need to add `nocolor` by some other great guy and programmer. :)

Great!
Not sure, it seems NoColor has little to do with KPHP.
